# Generated by Django 5.1 on 2024-08-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=100)),
                ('sip_calling_party', models.CharField(max_length=100)),
                ('sip_called_party', models.CharField(max_length=100)),
                ('sip_call_duration', models.IntegerField()),
                ('sip_call_status', models.CharField(max_length=100)),
                ('sip_rtp_l4_src_port', models.IntegerField()),
                ('sip_rtp_l4_dst_port', models.IntegerField()),
                ('rtp_in_jitter', models.IntegerField()),
                ('rtp_in_mos', models.DecimalField(decimal_places=1, max_digits=6)),
                ('pkt_loss_per', models.DecimalField(decimal_places=1, max_digits=6)),
                ('sip_calling_reg', models.CharField(max_length=100)),
                ('sip_called_reg', models.CharField(max_length=100)),
            ],
        ),
    ]
